# MirrorMD Local Development Compose
# Use this for local testing without Cloudflare Tunnel

services:
  mirrormd-app:
    build:
      context: .
      dockerfile: Containerfile
    container_name: mirrormd-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
