#!/usr/bin/env node
// Test script for PDF conversion
// Run with: node convert_test.js

const fs = require('fs').promises;
const path = require('path');
const { markdownToPdf, closeBrowser, THEMES } = require('./pdfConverter');

const TEST_MARKDOWN = `
# MirrorMD Test Document

This is a test document to verify PDF generation is working correctly.

## Features Tested

- **Bold text** and *italic text*
- Lists like this one
- Code snippets

## Code Example

\`\`\`javascript
function greet(name) {
  return \`Hello, \${name}!\`;
}

console.log(greet('World'));
\`\`\`

## Table Example

| Feature | Status |
|---------|--------|
| Markdown Parsing | ✅ Working |
| PDF Generation | ✅ Working |
| Solarized Styling | ✅ Working |

## Blockquote

> "The best way to predict the future is to create it."
> — Peter Drucker

---

### Inline Code

Use \`npm install\` to install dependencies.

### Links

Visit [GitHub](https://github.com) for more information.

---

*Generated by MirrorMD*
`;

async function runTest() {
  console.log('🧪 Starting PDF conversion tests...\n');
  
  const themes = Object.keys(THEMES);
  const results = [];
  
  try {
    await fs.mkdir(path.join(__dirname, '../temp'), { recursive: true });
    
    for (const theme of themes) {
      const startTime = Date.now();
      
      console.log(`📝 Testing theme: ${theme}...`);
      
      const pdfBuffer = await markdownToPdf(TEST_MARKDOWN, {
        theme,
        title: 'MirrorMD Test Document',
        showFooter: true
      });
      
      const outputPath = path.join(__dirname, `../temp/test-${theme}.pdf`);
      await fs.writeFile(outputPath, pdfBuffer);
      
      const endTime = Date.now();
      const duration = ((endTime - startTime) / 1000).toFixed(2);
      const size = (pdfBuffer.length / 1024).toFixed(2);
      
      results.push({ theme, size, duration, path: outputPath });
      
      console.log(`   ✅ ${theme}: ${size} KB in ${duration}s`);
    }
    
    console.log('\n📊 Summary:');
    console.log('─'.repeat(50));
    results.forEach(r => {
      console.log(`   ${r.theme.padEnd(20)} ${r.size.padStart(8)} KB   ${r.duration}s`);
    });
    console.log('─'.repeat(50));
    console.log(`\n📁 Output files in: ${path.join(__dirname, '../temp/')}\n`);
    
    return true;
  } catch (error) {
    console.error('❌ PDF conversion failed:', error.message);
    console.error(error.stack);
    return false;
  } finally {
    await closeBrowser();
  }
}

// Run the test
runTest()
  .then(success => {
    process.exit(success ? 0 : 1);
  })
  .catch(err => {
    console.error('Unexpected error:', err);
    process.exit(1);
  });
