// PDF Converter Module using Puppeteer
const puppeteer = require('puppeteer');
const fs = require('fs').promises;
const path = require('path');

// Available themes
const THEMES = {
  printer: 'theme-printer',
  'solarized-light': 'theme-solarized-light',
  'solarized-dark': 'theme-solarized-dark'
};

// Default PDF options
const DEFAULT_OPTIONS = {
  format: 'A4',
  margin: {
    top: '20mm',
    right: '20mm',
    bottom: '20mm',
    left: '20mm'
  },
  printBackground: true,
  displayHeaderFooter: false
};

// Load CSS from file
let printCSS = null;
async function getPrintCSS() {
  if (!printCSS) {
    const cssPath = path.join(__dirname, 'print.css');
    printCSS = await fs.readFile(cssPath, 'utf8');
  }
  return printCSS;
}

// Create browser instance
let browser = null;

async function getBrowser() {
  if (!browser) {
    browser = await puppeteer.launch({
      headless: true,
      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-gpu'
      ],
      executablePath: process.env.PUPPETEER_EXECUTABLE_PATH || undefined
    });
  }
  return browser;
}

// Convert HTML to PDF
async function htmlToPdf(html, options = {}) {
  const browser = await getBrowser();
  const page = await browser.newPage();

  try {
    // Get the theme class
    const theme = options.theme || 'solarized-light';
    const themeClass = THEMES[theme] || THEMES['solarized-light'];
    
    // Load CSS
    const css = await getPrintCSS();
    
    // Build header/footer if requested
    let headerTemplate = '';
    let footerTemplate = '';
    
    if (options.showHeader && options.title) {
      headerTemplate = `
        <div style="font-size: 10px; width: 100%; text-align: center; color: #666; padding: 5mm 20mm;">
          ${options.title}
        </div>
      `;
    }
    
    if (options.showFooter) {
      footerTemplate = `
        <div style="font-size: 9px; width: 100%; text-align: center; color: #888; padding: 5mm 20mm;">
          <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
          <span style="float: right;">Generated by MirrorMD</span>
        </div>
      `;
    }
    
    // Create full HTML document with styling
    const fullHtml = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="UTF-8">
          <style>${css}</style>
        </head>
        <body class="${themeClass}">
          ${html}
        </body>
      </html>
    `;

    // Set content and wait for images to load
    await page.setContent(fullHtml, { waitUntil: 'networkidle0', timeout: 30000 });
    
    // Additional wait for any lazy-loaded images
    await page.evaluate(() => {
      return Promise.all(
        Array.from(document.images)
          .filter(img => !img.complete)
          .map(img => new Promise((resolve, reject) => {
            img.onload = resolve;
            img.onerror = resolve; // Don't fail on broken images
            setTimeout(resolve, 5000); // Timeout after 5s per image
          }))
      );
    });

    const pdfOptions = {
      ...DEFAULT_OPTIONS,
      ...options,
      displayHeaderFooter: !!(options.showHeader || options.showFooter),
      headerTemplate: headerTemplate || '<span></span>',
      footerTemplate: footerTemplate || '<span></span>'
    };
    
    // Remove custom options that puppeteer doesn't understand
    delete pdfOptions.theme;
    delete pdfOptions.title;
    delete pdfOptions.showHeader;
    delete pdfOptions.showFooter;

    const pdfBuffer = await page.pdf(pdfOptions);
    return pdfBuffer;
  } finally {
    await page.close();
  }
}

// Convert Markdown to PDF
async function markdownToPdf(markdown, options = {}) {
  const { marked } = require('marked');
  
  // Custom renderer for images
  const renderer = new marked.Renderer();
  renderer.image = function(href, title, text) {
    // Handle both object format (new marked) and string format (old marked)
    if (typeof href === 'object') {
      text = href.text || '';
      title = href.title || '';
      href = href.href || '';
    }
    const titleAttr = title ? ` title="${title}"` : '';
    return `<img src="${href}" alt="${text}"${titleAttr} style="max-width: 100%; height: auto;">`;
  };

  marked.setOptions({
    breaks: true,
    gfm: true,
    renderer: renderer
  });

  const html = marked(markdown);
  return htmlToPdf(html, options);
}

// Cleanup browser on exit
async function closeBrowser() {
  if (browser) {
    await browser.close();
    browser = null;
  }
}

// Handle process termination
process.on('SIGINT', closeBrowser);
process.on('SIGTERM', closeBrowser);

module.exports = {
  htmlToPdf,
  markdownToPdf,
  closeBrowser,
  getPrintCSS,
  THEMES,
  DEFAULT_OPTIONS
};
